# Generated by Django 4.1.1 on 2022-10-10 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documento', '0001_initial'),
        ('tipoPtrab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ptrab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('data', models.DateField(auto_now=True, verbose_name='Data')),
                ('operacao', models.CharField(max_length=100, verbose_name='Operação')),
                ('acao', models.CharField(max_length=200, verbose_name='Ação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('documento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.documento', verbose_name='Documento')),
                ('tipo_ptrab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipoPtrab.tipoptrab', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'PTrab',
                'verbose_name_plural': 'PTrab',
                'ordering': ['numero'],
            },
        ),
    ]
