# Generated by Django 4.1.1 on 2022-10-09 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidade', '0004_alter_comandomilitararea_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Nr Documento')),
                ('data', models.DateField(verbose_name='Data')),
                ('secao', models.CharField(max_length=50, verbose_name='Seção')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('om', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidade.unidade', verbose_name='OM')),
            ],
            options={
                'verbose_name': 'Documentos',
                'verbose_name_plural': 'Documentos',
                'ordering': ['numero'],
            },
        ),
    ]
