# Generated by Django 4.1.2 on 2022-10-23 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipoDespesa', '0001_initial'),
        ('despesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['unidade_id'], 'verbose_name': 'Despesa', 'verbose_name_plural': 'Despesas'},
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='data',
        ),
        migrations.AlterField(
            model_name='despesa',
            name='nd',
            field=models.CharField(choices=[(15, '33.90.15'), (30, '33.90.30'), (33, '33.90.33'), (39, '33.90.39'), (40, '44.90.40'), (52, '44.90.52')], max_length=5, verbose_name='ND'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tipo_despesa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipoDespesa.tipodespesa', verbose_name='Tipo'),
        ),
    ]
