# Generated by Django 4.1.1 on 2022-10-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localidade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidade',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='criado_em',
        ),
    ]
