# Generated by Django 4.1.1 on 2022-10-12 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localidade', '0002_remove_cidade_atualizado_em_remove_cidade_criado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localidade',
            name='cidade_id',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
    ]
