# Generated by Django 4.1.1 on 2022-10-12 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localidade', '0003_remove_localidade_cidade_id_delete_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('estado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localidade.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome'],
            },
        ),
        migrations.DeleteModel(
            name='Localidade',
        ),
    ]
