# Generated by Django 4.1.1 on 2022-10-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codug', models.CharField(help_text='Digite o codug da OM, por exemplo: 160539', max_length=7, verbose_name='CODUG')),
                ('autonomia', models.BooleanField(help_text='Marque se a OM tem autonomia administrativa', verbose_name='Autonomia')),
                ('nome', models.CharField(help_text='Digite o nome da OM, por exemplo: Comando de Operações Terrestres', max_length=50, verbose_name='Nome OM')),
                ('rm', models.IntegerField(choices=[(1, '1ª RM'), (2, '2ª RM'), (3, '3ª RM'), (4, '4ª RM'), (5, '5ª RM'), (6, '6ª RM'), (7, '7ª RM'), (8, '8ª RM'), (9, '9ª RM'), (10, '10ª RM'), (11, '11ª RM'), (12, '12ª RM')], verbose_name='RM')),
                ('c_mil_a', models.IntegerField(choices=[(1, 'CMA'), (2, 'CMN'), (3, 'CMNE'), (4, 'CMSE'), (5, 'CML'), (6, 'CMS'), (7, 'CMO'), (8, 'CMP')], verbose_name='C Mil A')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
