# Generated by Django 4.1.1 on 2022-10-08 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComandoMilitarArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviatura', models.CharField(max_length=5, verbose_name='Abreviatura')),
                ('nome', models.CharField(max_length=50, verbose_name='C Mil A')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='c_mil_a',
        ),
        migrations.CreateModel(
            name='RegiaoMilitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviatura', models.CharField(max_length=5, verbose_name='Abreviatura')),
                ('nome', models.CharField(max_length=50, verbose_name='RM')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('c_mil_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidade.comandomilitararea', verbose_name='C Mil A')),
            ],
        ),
        migrations.AlterField(
            model_name='unidade',
            name='rm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidade.regiaomilitar', verbose_name='RM'),
        ),
    ]
