# Generated by Django 4.1.1 on 2022-10-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0002_comandomilitararea_remove_unidade_c_mil_a_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comandomilitararea',
            options={'verbose_name': 'C Mil A', 'verbose_name_plural': 'C Mil A'},
        ),
        migrations.AlterModelOptions(
            name='regiaomilitar',
            options={'verbose_name': 'RM', 'verbose_name_plural': 'RM'},
        ),
        migrations.AlterModelOptions(
            name='unidade',
            options={'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AlterField(
            model_name='regiaomilitar',
            name='abreviatura',
            field=models.CharField(max_length=10, verbose_name='Abreviatura'),
        ),
    ]
